### ISSUE TITLE
Testing case with macroquad/miniquad

### ISSUE THREAD

**Issue by FuriouZz** [studio-lagier/wasm-2d-rendering-test#1]
I found interesting your tests, but I think you completely forget to try macroquad in your tests. Works on wasm, extremely lightweight, you code fully in Rust, WebGL for the rendering, etc...

**Comment by tomlagier** [comment]
I'm pretty new to the Rust gamedev ecosystem, so I didn't even know about `macroquad`! It looks great, I'll give it a shot when I can.

**Comment by tomlagier** [comment]
I checked it out, it's interesting - very nice API, but the performance was not so good. I was averaging around 60 FPS in release mode. You can see the code on the `macroquad` branch. Run like so:

`cargo build --target wasm32-unknown-unknown --release`
`cd target/wasm32-unknown-unknown/release`
`cp ../../../www/index.html .`
`python -m http.server 8001`

Open `localhost:8001`. I'm not sure if `macroquad` is capping FPS or not, I dug in to the perf a little but it's hard to tell because all of the calls are happening on the WASM side so you can't get a good aggregate view of what's taking a long time.
